call truffle-flattener contracts\BentoBox.sol > flat\BentoBox.sol
call truffle-flattener contracts\LendingPair.sol > flat\LendingPair.sol
call truffle-flattener contracts\swappers\SushiSwapSwapper.sol > flat\SushiSwapSwapper.sol
call truffle-flattener contracts\oracles\PeggedOracle.sol > flat\PeggedOracle.sol
call truffle-flattener contracts\oracles\CompoundOracle.sol > flat\CompoundOracle.sol
call truffle-flattener contracts\oracles\ChainLinkOracle.sol > flat\ChainLinkOracle.sol
call truffle-flattener contracts\oracles\SimpleSLPTWAP0Oracle.sol > flat\SimpleSLPTWAP0Oracle.sol
call truffle-flattener contracts\oracles\SimpleSLPTWAP1Oracle.sol > flat\SimpleSLPTWAP1Oracle.sol
call truffle-flattener contracts\oracles\CompositeOracle.sol > flat\CompositeOracle.sol
call truffle-flattener contracts\BentoHelper.sol > flat\BentoHelper.sol