/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ISwapperInterface extends ethers.utils.Interface {
  functions: {
    "swap(address,address,address,uint256,uint256)": FunctionFragment;
    "swapExact(address,address,address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "swap",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExact",
    values: [string, string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapExact", data: BytesLike): Result;

  events: {};
}

export class ISwapper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: ISwapperInterface;

  functions: {
    swap(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swap(address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    swapExact(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swapExact(address,address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  swap(
    fromToken: string,
    toToken: string,
    recipient: string,
    amountToMin: BigNumberish,
    shareFrom: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swap(address,address,address,uint256,uint256)"(
    fromToken: string,
    toToken: string,
    recipient: string,
    amountToMin: BigNumberish,
    shareFrom: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  swapExact(
    fromToken: string,
    toToken: string,
    recipient: string,
    refundTo: string,
    shareFromSupplied: BigNumberish,
    shareToExact: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swapExact(address,address,address,address,uint256,uint256)"(
    fromToken: string,
    toToken: string,
    recipient: string,
    refundTo: string,
    shareFromSupplied: BigNumberish,
    shareToExact: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    swap(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { extraAmount: BigNumber; shareTo: BigNumber }
    >;

    "swap(address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { extraAmount: BigNumber; shareTo: BigNumber }
    >;

    swapExact(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        shareUsed: BigNumber;
        shareReturned: BigNumber;
      }
    >;

    "swapExact(address,address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        shareUsed: BigNumber;
        shareReturned: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    swap(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "swap(address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    swapExact(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "swapExact(address,address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    swap(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swap(address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      amountToMin: BigNumberish,
      shareFrom: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    swapExact(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swapExact(address,address,address,address,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      recipient: string,
      refundTo: string,
      shareFromSupplied: BigNumberish,
      shareToExact: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
