/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bentoBoxFlatSol from "./BentoBoxFlat.sol";
export * as boringBatchableSol from "./BoringBatchable.sol";
export * as boringOwnableSol from "./BoringOwnable.sol";
export * as compoundStrategySol from "./CompoundStrategy.sol";
export * as iFlashLoanSol from "./IFlashLoan.sol";
export * as sushiStrategySol from "./SushiStrategy.sol";
export * as sushiStrategyFlatSol from "./SushiStrategyFlat.sol";
export * as helloworldSol from "./helloworld.sol";
export * as salarySol from "./salary.sol";
export { BentoBox__factory } from "./BentoBox__factory";
export { BoringFactory__factory } from "./BoringFactory__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IMasterContract__factory } from "./IMasterContract__factory";
export { IStrategy__factory } from "./IStrategy__factory";
export { IWETH__factory } from "./IWETH__factory";
export { MasterContractManager__factory } from "./MasterContractManager__factory";
